kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


patches:
- patch: |-
    - op: add
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/1/nodePort
      value: 30443
  target:
    kind: Service
    name: argocd-server


# brew install argocd
# kubectl exec -it $(kubectl get pods -n argocd | grep argocd-server | tail -n 1 | awk '{print $1}') -n argocd  -- argocd admin initial-password -n argocd ; argocd login 127.0.0.1:30443
# argocd account update-password
