kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: stg


labels:
- includeSelectors: true
  pairs:
    app.gigcloud.io/environment: staging

nameSuffix: -staging

resources:
- namespace.yaml
- ../../base

patches:
- path: configmap-patch.yaml

- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30081
  target:
    kind: Service
    name: nginx-service
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: nginx-deployment